const GET_MOVIE_LIST = {
  GET_MOVIE_LIST_INITLIZATION: "GET_MOVIE_LIST_INITLIZATION",
  GET_MOVIE_LIST_SUCCESS: "GET_MOVIE_LIST_SUCCESS",
  GET_MOVIE_LIST_ERORR: "GET_MOVIE_LIST_ERORR",
};

const SEARCH_MOVIE_LIST = {
  SEARCH_MOVIE_LIST_INITLIZATION: "SEARCH_MOVIE_LIST_INITLIZATION",
  SEARCH_MOVIE_LIST_SUCCESS: "SEARCH_MOVIE_LIST_SUCCESS",
  SEARCH_MOVIE_LIST_ERORR: "SEARCH_MOVIE_LIST_ERORR",
};


const GET_MOVIE_DETAIL = {
  GET_MOVIE_DETAIL_INITLIZATION: "GET_MOVIE_DETAIL_INITLIZATION",
  GET_MOVIE_DETAIL_SUCCESS: "GET_MOVIE_DETAIL_SUCCESS",
  GET_MOVIE_DETAIL_ERORR: "GET_MOVIE_DETAIL_ERORR",
};

const GET_MOVIE_CAST_DETAIL = {
  GET_MOVIE_CAST_DETAIL_INITLIZATION: "GET_MOVIE_CAST_DETAIL_INITLIZATION",
  GET_MOVIE_CAST_DETAIL_SUCCESS: "GET_MOVIE_CAST_DETAIL_SUCCESS",
  GET_MOVIE_CAST_DETAIL_ERORR: "GET_MOVIE_CAST_DETAIL_ERORR",
};

const SET_IS_SEARCH="SET_IS_SEARCH";

 export {
  GET_MOVIE_LIST,
  SEARCH_MOVIE_LIST,
  GET_MOVIE_DETAIL,
  GET_MOVIE_CAST_DETAIL,
  SET_IS_SEARCH
 }